import type { Doctor, Department, NewsArticle, Testimonial, Stat } from '@/types'

export const departments: Department[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Advanced cardiac care with state-of-the-art imaging, interventional procedures, and comprehensive heart failure management.',
    icon: 'favorite',
    specialties: ['Interventional Cardiology', 'Electrophysiology', 'Heart Failure', 'Cardiac Imaging'],
    doctors: 18,
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'neurology',
    name: 'Neurology',
    description: 'Comprehensive neurological care encompassing stroke management, epilepsy, neurodegenerative diseases, and minimally invasive neurosurgery.',
    icon: 'neurology',
    specialties: ['Stroke', 'Epilepsy', 'Multiple Sclerosis', 'Neurosurgery'],
    doctors: 14,
    image: 'https://images.unsplash.com/photo-1631815588090-d1bcbe9a8545?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'oncology',
    name: 'Oncology',
    description: 'Cutting-edge cancer care using molecular profiling, immunotherapy, robotic-assisted surgery, and precision radiation therapy.',
    icon: 'labs',
    specialties: ['Medical Oncology', 'Radiation Oncology', 'Surgical Oncology', 'Hematology'],
    doctors: 22,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    featured: true,
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    description: 'Compassionate pediatric care from newborns to adolescents, including specialized NICU, pediatric surgery, and developmental medicine.',
    icon: 'child_care',
    specialties: ['Neonatology', 'Pediatric Surgery', 'Developmental Medicine', 'Pediatric Oncology'],
    doctors: 16,
    image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    description: 'Expert musculoskeletal care including joint replacement, sports medicine, spine surgery, and advanced rehabilitation programs.',
    icon: 'accessibility_new',
    specialties: ['Joint Replacement', 'Sports Medicine', 'Spine Surgery', 'Trauma'],
    doctors: 12,
    image: 'https://images.unsplash.com/photo-1583912267550-d974a0d79b6e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'dermatology',
    name: 'Dermatology',
    description: 'Medical and cosmetic dermatology services including skin cancer screening, laser treatments, and advanced wound care.',
    icon: 'health_and_beauty',
    specialties: ['Medical Dermatology', 'Cosmetic Dermatology', 'Dermatologic Surgery', 'Phototherapy'],
    doctors: 9,
  },
  {
    id: 'gastroenterology',
    name: 'Gastroenterology',
    description: 'Digestive health expertise spanning endoscopy, liver disease, inflammatory bowel disease, and minimally invasive procedures.',
    icon: 'gastroenterology',
    specialties: ['Endoscopy', 'Hepatology', 'IBD', 'Colorectal Surgery'],
    doctors: 11,
  },
  {
    id: 'maternity',
    name: "Women's Health",
    description: "Comprehensive women's healthcare from reproductive medicine and high-risk obstetrics to gynecologic oncology.",
    icon: 'pregnant_woman',
    specialties: ['Obstetrics', 'Gynecology', 'Reproductive Medicine', 'Gynecologic Oncology'],
    doctors: 15,
  },
  {
    id: 'diagnostics',
    name: 'Diagnostic Imaging',
    description: 'Advanced imaging with 3T MRI, PET/CT, interventional radiology, and AI-assisted diagnostic interpretation.',
    icon: 'radiology',
    specialties: ['MRI & CT', 'Nuclear Medicine', 'Interventional Radiology', 'Ultrasound'],
    doctors: 8,
  },
]

export const doctors: Doctor[] = [
  {
    id: 'dr-elena-sterling',
    name: 'Dr. Elena Sterling',
    specialty: 'Cardiology',
    department: 'cardiology',
    experience: 22,
    education: 'Johns Hopkins University School of Medicine',
    qualifications: ['MD, FACC', 'Board Certified Interventional Cardiologist', 'Fellow, American College of Cardiology'],
    availability: 'Available',
    bio: 'Dr. Sterling is the Chief Medical Officer and leads our world-renowned cardiology program. With over two decades in interventional cardiology, she has pioneered minimally invasive techniques that have transformed patient outcomes.',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    consultations: 4200,
  },
  {
    id: 'dr-marcus-thorne',
    name: 'Dr. Marcus Thorne',
    specialty: 'Neurosurgery',
    department: 'neurology',
    experience: 18,
    education: 'Harvard Medical School',
    qualifications: ['MD, FAANS', 'Board Certified Neurosurgeon', 'Fellowship in Minimally Invasive Spine Surgery'],
    availability: 'Available',
    bio: "As Head of Surgery, Dr. Thorne specializes in complex neurosurgical procedures. His groundbreaking work in AI-assisted surgical navigation has significantly reduced recovery times.",
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    consultations: 3100,
  },
  {
    id: 'dr-sarah-lang',
    name: 'Dr. Sarah Lang',
    specialty: 'Oncology',
    department: 'oncology',
    experience: 15,
    education: 'Stanford University School of Medicine',
    qualifications: ['MD, PhD', 'Board Certified Medical Oncologist', 'Director of Innovation'],
    availability: 'Busy',
    bio: "Dr. Lang directs our precision oncology program, leveraging molecular profiling and next-generation immunotherapies. Her research has contributed to breakthrough treatments.",
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    consultations: 2800,
  },
  {
    id: 'dr-julian-vance',
    name: 'Dr. Julian Vance',
    specialty: 'Orthopedic Surgery',
    department: 'orthopedics',
    experience: 20,
    education: 'Mayo Clinic Alix School of Medicine',
    qualifications: ['MD, FAAOS', 'Board Certified Orthopedic Surgeon', 'Sports Medicine Specialist'],
    availability: 'Available',
    bio: "Dr. Vance founded Clinical Excellence in 1984 with a vision to redefine healthcare. His expertise in robotic-assisted joint replacement has helped thousands of patients regain mobility.",
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    consultations: 5100,
  },
  {
    id: 'dr-priya-mehta',
    name: 'Dr. Priya Mehta',
    specialty: 'Pediatrics',
    department: 'pediatrics',
    experience: 12,
    education: 'University of California, San Francisco',
    qualifications: ['MD', 'Board Certified Pediatrician', 'NICU Specialist'],
    availability: 'Available',
    bio: 'Dr. Mehta leads our pediatric department with extraordinary dedication. Her compassionate approach and clinical expertise have made her one of the most trusted physicians in pediatric critical care.',
    image: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    consultations: 2200,
  },
  {
    id: 'dr-james-hartwell',
    name: 'Dr. James Hartwell',
    specialty: 'Gastroenterology',
    department: 'gastroenterology',
    experience: 16,
    education: 'University of Pennsylvania School of Medicine',
    qualifications: ['MD, AGAF', 'Board Certified Gastroenterologist', 'Advanced Endoscopy Fellow'],
    availability: 'Available',
    bio: 'Dr. Hartwell is a pioneer in advanced endoscopic techniques, having performed over 10,000 procedures. His expertise in IBD management has attracted patients globally.',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=400&q=80',
    rating: 4.7,
    consultations: 3400,
  },
  {
    id: 'dr-amara-osei',
    name: 'Dr. Amara Osei',
    specialty: "Women's Health",
    department: 'maternity',
    experience: 14,
    education: 'Columbia University College of Physicians and Surgeons',
    qualifications: ['MD, FACOG', 'Board Certified OB/GYN', 'Maternal-Fetal Medicine Specialist'],
    availability: 'Busy',
    bio: "Dr. Osei specializes in high-risk obstetrics and maternal-fetal medicine. Her commitment to reducing maternal mortality has earned her recognition as one of America's top OB/GYNs.",
    image: 'https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?auto=format&fit=crop&w=400&q=80',
    rating: 4.9,
    consultations: 2900,
  },
  {
    id: 'dr-chen-wei',
    name: 'Dr. Chen Wei',
    specialty: 'Radiology',
    department: 'diagnostics',
    experience: 11,
    education: 'Yale School of Medicine',
    qualifications: ['MD, PhD', 'Board Certified Radiologist', 'Interventional Radiology Specialist'],
    availability: 'Available',
    bio: 'Dr. Wei combines advanced imaging expertise with cutting-edge AI tools to deliver highly accurate diagnoses. His research in AI-assisted image interpretation is published in leading journals.',
    image: 'https://images.unsplash.com/photo-1622902046580-2b47f47f5471?auto=format&fit=crop&w=400&q=80',
    rating: 4.8,
    consultations: 1800,
  },
]

export const newsArticles: NewsArticle[] = [
  {
    id: 'ai-cardiac-care',
    title: 'AI-Assisted Cardiac Imaging: Redefining Precision in Heart Disease Diagnosis',
    excerpt: 'Our cardiology team has partnered with leading AI researchers to deploy advanced neural networks that detect subtle cardiac anomalies earlier and more accurately than ever before.',
    author: 'Dr. Elena Sterling',
    authorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Chief Medical Officer & Cardiologist',
    publishDate: '2026-03-28',
    category: 'Clinical Innovation',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&w=1200&q=80',
    featured: true,
    readTime: 7,
  },
  {
    id: 'robotic-surgery',
    title: 'Fifth-Generation Robotic Surgical System Enhances Precision for Complex Procedures',
    excerpt: 'Clinical Excellence becomes the first hospital in the region to deploy the latest robotic surgical platform, enabling sub-millimeter precision in minimally invasive operations.',
    author: 'Dr. Marcus Thorne',
    authorImage: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Head of Surgery',
    publishDate: '2026-03-15',
    category: 'Technology',
    image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
    readTime: 5,
  },
  {
    id: 'immunotherapy-breakthrough',
    title: 'Breakthrough Immunotherapy Protocol Shows 94% Response Rate in Phase III Trial',
    excerpt: "Our oncology team's novel combination immunotherapy approach has demonstrated remarkable efficacy in treating advanced melanoma, offering new hope.",
    author: 'Dr. Sarah Lang',
    authorImage: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Director of Innovation & Oncologist',
    publishDate: '2026-02-22',
    category: 'Research',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
    readTime: 9,
  },
  {
    id: 'pediatric-cardiac',
    title: 'Understanding Congenital Heart Defects: Early Detection Saves Lives',
    excerpt: 'Early screening programs are transforming outcomes for children with congenital heart conditions. Our team explains the latest advances in fetal and neonatal cardiac screening.',
    author: 'Dr. Priya Mehta',
    authorImage: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Pediatric Specialist',
    publishDate: '2026-02-10',
    category: 'Pediatrics',
    image: 'https://images.unsplash.com/photo-1530026405186-ed1f139313f8?auto=format&fit=crop&w=800&q=80',
    readTime: 6,
  },
  {
    id: 'women-heart-health',
    title: 'Heart Disease in Women: Why Symptoms Present Differently',
    excerpt: 'Cardiovascular disease remains the leading cause of death in women, yet symptoms often differ from classic presentations. Understanding these differences is critical.',
    author: 'Dr. Elena Sterling',
    authorImage: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Cardiologist & CMO',
    publishDate: '2026-01-28',
    category: 'Patient Education',
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
    readTime: 8,
  },
  {
    id: 'gut-microbiome',
    title: 'The Gut-Brain Axis: How Microbiome Research Reshapes Neurological Care',
    excerpt: "Emerging research is revealing surprising connections between intestinal health and neurological conditions, from depression to Parkinson's disease.",
    author: 'Dr. James Hartwell',
    authorImage: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=100&q=80',
    authorTitle: 'Gastroenterologist',
    publishDate: '2026-01-14',
    category: 'Research',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=800&q=80',
    readTime: 11,
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    patientName: 'Margaret K.',
    condition: 'Cardiac Surgery',
    doctor: 'Dr. Elena Sterling',
    rating: 5,
    text: "After my diagnosis, I was terrified. Dr. Sterling and her team not only treated my condition with extraordinary skill — they restored my confidence in life. The level of personalized care I received was unlike anything I've experienced at other institutions.",
    date: '2026-02-15',
  },
  {
    id: '2',
    patientName: 'Thomas R.',
    condition: 'Spinal Surgery',
    doctor: 'Dr. Marcus Thorne',
    rating: 5,
    text: "I'd been told by three other surgeons that my condition was inoperable. Dr. Thorne took a different approach, and today I'm hiking again. Clinical Excellence is not just a name — it's their actual standard of care.",
    date: '2026-01-20',
  },
  {
    id: '3',
    patientName: 'Lena V.',
    condition: 'Breast Cancer Treatment',
    doctor: 'Dr. Sarah Lang',
    rating: 5,
    text: "The precision oncology program here is extraordinary. Dr. Lang designed a treatment plan specifically for my genetic profile. Eighteen months later, I'm cancer-free and grateful every single day.",
    date: '2025-12-05',
  },
]

export const stats: Stat[] = [
  { value: '99%', label: 'Patient Satisfaction', icon: 'thumb_up' },
  { value: '250+', label: 'Global Specialists', icon: 'groups' },
  { value: '15', label: 'Centers of Excellence', icon: 'workspace_premium' },
  { value: 'A+', label: 'Accreditation Rating', icon: 'verified' },
]

export const timeSlots = [
  '08:00 AM', '08:30 AM', '09:00 AM', '09:30 AM',
  '10:00 AM', '10:30 AM', '11:00 AM', '11:30 AM',
  '02:00 PM', '02:30 PM', '03:00 PM', '03:30 PM',
  '04:00 PM', '04:30 PM', '05:00 PM', '05:30 PM',
]

export const insuranceProviders = [
  'Aetna', 'Blue Cross Blue Shield', 'Cigna', 'Humana',
  'Kaiser Permanente', 'UnitedHealthcare', 'Medicare', 'Medicaid',
  'Self-Pay', 'Other',
]
